// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	common.proto
	errno.proto
	Message.proto
	msgid.proto

It has these top-level messages:
	UserInfo
	KeepAlive
	CSLoginReq
	SCLoginRsp
	CSCreateRoomReq
	SCCreateRoomRsp
	CSEnterRoomReq
	SCEnterRoomRsp
	SCEnterRoomNtf
	SCRoomUserInfos
	CSLeaveRoomReq
	SCLeaveRoomRsp
	SCLeaveRoomNtf
	SCGameRoomInfo
	CSReadyReq
	SCReadyRsp
	SCReadyNtf
	CSCancelReadyReq
	SCCancelReadyRsp
	SCCancelReadyNtf
	SCGameStartNtf
	SCGameEndNtf
	SCRoundEndNtf
	Pb
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 游戏id
type GameId int32

const (
	GameId_None GameId = 0
	GameId_Hzmj GameId = 101
	GameId_Ddz  GameId = 102
)

var GameId_name = map[int32]string{
	0:   "None",
	101: "Hzmj",
	102: "Ddz",
}
var GameId_value = map[string]int32{
	"None": 0,
	"Hzmj": 101,
	"Ddz":  102,
}

func (x GameId) String() string {
	return proto.EnumName(GameId_name, int32(x))
}
func (GameId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 房间状态
type RoomState int32

const (
	RoomState_Idle    RoomState = 0
	RoomState_Wait    RoomState = 1
	RoomState_Gaming  RoomState = 2
	RoomState_Closing RoomState = 3
)

var RoomState_name = map[int32]string{
	0: "Idle",
	1: "Wait",
	2: "Gaming",
	3: "Closing",
}
var RoomState_value = map[string]int32{
	"Idle":    0,
	"Wait":    1,
	"Gaming":  2,
	"Closing": 3,
}

func (x RoomState) String() string {
	return proto.EnumName(RoomState_name, int32(x))
}
func (RoomState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 离开房间原因
type LeaveReason int32

const (
	LeaveReason_Unknown   LeaveReason = 0
	LeaveReason_ConnBreak LeaveReason = 1
	LeaveReason_Kick      LeaveReason = 2
	LeaveReason_Force     LeaveReason = 3
	LeaveReason_UserOp    LeaveReason = 4
)

var LeaveReason_name = map[int32]string{
	0: "Unknown",
	1: "ConnBreak",
	2: "Kick",
	3: "Force",
	4: "UserOp",
}
var LeaveReason_value = map[string]int32{
	"Unknown":   0,
	"ConnBreak": 1,
	"Kick":      2,
	"Force":     3,
	"UserOp":    4,
}

func (x LeaveReason) String() string {
	return proto.EnumName(LeaveReason_name, int32(x))
}
func (LeaveReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 房间结束原因
type RoomCloseReason int32

const (
	RoomCloseReason_Normal     RoomCloseReason = 0
	RoomCloseReason_Expire     RoomCloseReason = 1
	RoomCloseReason_ForceClose RoomCloseReason = 2
	RoomCloseReason_Empty      RoomCloseReason = 3
)

var RoomCloseReason_name = map[int32]string{
	0: "Normal",
	1: "Expire",
	2: "ForceClose",
	3: "Empty",
}
var RoomCloseReason_value = map[string]int32{
	"Normal":     0,
	"Expire":     1,
	"ForceClose": 2,
	"Empty":      3,
}

func (x RoomCloseReason) String() string {
	return proto.EnumName(RoomCloseReason_name, int32(x))
}
func (RoomCloseReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 游戏状态
type UserGameState int32

const (
	UserGameState_Watching UserGameState = 0
	UserGameState_UnReady  UserGameState = 1
	UserGameState_Ready    UserGameState = 2
	UserGameState_Playing  UserGameState = 3
)

var UserGameState_name = map[int32]string{
	0: "Watching",
	1: "UnReady",
	2: "Ready",
	3: "Playing",
}
var UserGameState_value = map[string]int32{
	"Watching": 0,
	"UnReady":  1,
	"Ready":    2,
	"Playing":  3,
}

func (x UserGameState) String() string {
	return proto.EnumName(UserGameState_name, int32(x))
}
func (UserGameState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UserInfo struct {
	Userid   int64  `protobuf:"varint,1,opt,name=userid" json:"userid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Header   string `protobuf:"bytes,3,opt,name=header" json:"header,omitempty"`
	Seat     int32  `protobuf:"varint,4,opt,name=seat" json:"seat,omitempty"`
	State    uint32 `protobuf:"varint,5,opt,name=state" json:"state,omitempty"`
	Jdata    string `protobuf:"bytes,6,opt,name=jdata" json:"jdata,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetUserid() int64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *UserInfo) GetSeat() int32 {
	if m != nil {
		return m.Seat
	}
	return 0
}

func (m *UserInfo) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *UserInfo) GetJdata() string {
	if m != nil {
		return m.Jdata
	}
	return ""
}

type KeepAlive struct {
}

func (m *KeepAlive) Reset()                    { *m = KeepAlive{} }
func (m *KeepAlive) String() string            { return proto.CompactTextString(m) }
func (*KeepAlive) ProtoMessage()               {}
func (*KeepAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CSLoginReq struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Passwd  string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Gameid  int32  `protobuf:"varint,3,opt,name=gameid" json:"gameid,omitempty"`
	Jdata   string `protobuf:"bytes,4,opt,name=jdata" json:"jdata,omitempty"`
}

func (m *CSLoginReq) Reset()                    { *m = CSLoginReq{} }
func (m *CSLoginReq) String() string            { return proto.CompactTextString(m) }
func (*CSLoginReq) ProtoMessage()               {}
func (*CSLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CSLoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CSLoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *CSLoginReq) GetGameid() int32 {
	if m != nil {
		return m.Gameid
	}
	return 0
}

func (m *CSLoginReq) GetJdata() string {
	if m != nil {
		return m.Jdata
	}
	return ""
}

type SCLoginRsp struct {
	Result int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Gameid int32  `protobuf:"varint,2,opt,name=gameid" json:"gameid,omitempty"`
	Jdata  string `protobuf:"bytes,3,opt,name=jdata" json:"jdata,omitempty"`
}

func (m *SCLoginRsp) Reset()                    { *m = SCLoginRsp{} }
func (m *SCLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*SCLoginRsp) ProtoMessage()               {}
func (*SCLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SCLoginRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SCLoginRsp) GetGameid() int32 {
	if m != nil {
		return m.Gameid
	}
	return 0
}

func (m *SCLoginRsp) GetJdata() string {
	if m != nil {
		return m.Jdata
	}
	return ""
}

type CSCreateRoomReq struct {
	Passwd string `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Round  int32  `protobuf:"varint,3,opt,name=round" json:"round,omitempty"`
	Jdata  string `protobuf:"bytes,4,opt,name=jdata" json:"jdata,omitempty"`
}

func (m *CSCreateRoomReq) Reset()                    { *m = CSCreateRoomReq{} }
func (m *CSCreateRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CSCreateRoomReq) ProtoMessage()               {}
func (*CSCreateRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CSCreateRoomReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *CSCreateRoomReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CSCreateRoomReq) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *CSCreateRoomReq) GetJdata() string {
	if m != nil {
		return m.Jdata
	}
	return ""
}

type SCCreateRoomRsp struct {
	Result int32  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Roomid int64  `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
	Jdata  string `protobuf:"bytes,3,opt,name=jdata" json:"jdata,omitempty"`
}

func (m *SCCreateRoomRsp) Reset()                    { *m = SCCreateRoomRsp{} }
func (m *SCCreateRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*SCCreateRoomRsp) ProtoMessage()               {}
func (*SCCreateRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SCCreateRoomRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SCCreateRoomRsp) GetRoomid() int64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *SCCreateRoomRsp) GetJdata() string {
	if m != nil {
		return m.Jdata
	}
	return ""
}

type CSEnterRoomReq struct {
	Roomid int64  `protobuf:"varint,1,opt,name=roomid" json:"roomid,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *CSEnterRoomReq) Reset()                    { *m = CSEnterRoomReq{} }
func (m *CSEnterRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CSEnterRoomReq) ProtoMessage()               {}
func (*CSEnterRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CSEnterRoomReq) GetRoomid() int64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *CSEnterRoomReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SCEnterRoomRsp struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Roomid int64 `protobuf:"varint,2,opt,name=roomid" json:"roomid,omitempty"`
}

func (m *SCEnterRoomRsp) Reset()                    { *m = SCEnterRoomRsp{} }
func (m *SCEnterRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*SCEnterRoomRsp) ProtoMessage()               {}
func (*SCEnterRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SCEnterRoomRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *SCEnterRoomRsp) GetRoomid() int64 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

type SCEnterRoomNtf struct {
	Uinfo *UserInfo `protobuf:"bytes,1,opt,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCEnterRoomNtf) Reset()                    { *m = SCEnterRoomNtf{} }
func (m *SCEnterRoomNtf) String() string            { return proto.CompactTextString(m) }
func (*SCEnterRoomNtf) ProtoMessage()               {}
func (*SCEnterRoomNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SCEnterRoomNtf) GetUinfo() *UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type SCRoomUserInfos struct {
	Uinfo []*UserInfo `protobuf:"bytes,1,rep,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCRoomUserInfos) Reset()                    { *m = SCRoomUserInfos{} }
func (m *SCRoomUserInfos) String() string            { return proto.CompactTextString(m) }
func (*SCRoomUserInfos) ProtoMessage()               {}
func (*SCRoomUserInfos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SCRoomUserInfos) GetUinfo() []*UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type CSLeaveRoomReq struct {
	Reason int32 `protobuf:"varint,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *CSLeaveRoomReq) Reset()                    { *m = CSLeaveRoomReq{} }
func (m *CSLeaveRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CSLeaveRoomReq) ProtoMessage()               {}
func (*CSLeaveRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CSLeaveRoomReq) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type SCLeaveRoomRsp struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SCLeaveRoomRsp) Reset()                    { *m = SCLeaveRoomRsp{} }
func (m *SCLeaveRoomRsp) String() string            { return proto.CompactTextString(m) }
func (*SCLeaveRoomRsp) ProtoMessage()               {}
func (*SCLeaveRoomRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SCLeaveRoomRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SCLeaveRoomNtf struct {
	Uinfo *UserInfo `protobuf:"bytes,1,opt,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCLeaveRoomNtf) Reset()                    { *m = SCLeaveRoomNtf{} }
func (m *SCLeaveRoomNtf) String() string            { return proto.CompactTextString(m) }
func (*SCLeaveRoomNtf) ProtoMessage()               {}
func (*SCLeaveRoomNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SCLeaveRoomNtf) GetUinfo() *UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type SCGameRoomInfo struct {
	Uinfo *UserInfo `protobuf:"bytes,1,opt,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCGameRoomInfo) Reset()                    { *m = SCGameRoomInfo{} }
func (m *SCGameRoomInfo) String() string            { return proto.CompactTextString(m) }
func (*SCGameRoomInfo) ProtoMessage()               {}
func (*SCGameRoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SCGameRoomInfo) GetUinfo() *UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type CSReadyReq struct {
}

func (m *CSReadyReq) Reset()                    { *m = CSReadyReq{} }
func (m *CSReadyReq) String() string            { return proto.CompactTextString(m) }
func (*CSReadyReq) ProtoMessage()               {}
func (*CSReadyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type SCReadyRsp struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SCReadyRsp) Reset()                    { *m = SCReadyRsp{} }
func (m *SCReadyRsp) String() string            { return proto.CompactTextString(m) }
func (*SCReadyRsp) ProtoMessage()               {}
func (*SCReadyRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SCReadyRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SCReadyNtf struct {
	Uinfo *UserInfo `protobuf:"bytes,1,opt,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCReadyNtf) Reset()                    { *m = SCReadyNtf{} }
func (m *SCReadyNtf) String() string            { return proto.CompactTextString(m) }
func (*SCReadyNtf) ProtoMessage()               {}
func (*SCReadyNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SCReadyNtf) GetUinfo() *UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type CSCancelReadyReq struct {
}

func (m *CSCancelReadyReq) Reset()                    { *m = CSCancelReadyReq{} }
func (m *CSCancelReadyReq) String() string            { return proto.CompactTextString(m) }
func (*CSCancelReadyReq) ProtoMessage()               {}
func (*CSCancelReadyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type SCCancelReadyRsp struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *SCCancelReadyRsp) Reset()                    { *m = SCCancelReadyRsp{} }
func (m *SCCancelReadyRsp) String() string            { return proto.CompactTextString(m) }
func (*SCCancelReadyRsp) ProtoMessage()               {}
func (*SCCancelReadyRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SCCancelReadyRsp) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SCCancelReadyNtf struct {
	Uinfo *UserInfo `protobuf:"bytes,1,opt,name=uinfo" json:"uinfo,omitempty"`
}

func (m *SCCancelReadyNtf) Reset()                    { *m = SCCancelReadyNtf{} }
func (m *SCCancelReadyNtf) String() string            { return proto.CompactTextString(m) }
func (*SCCancelReadyNtf) ProtoMessage()               {}
func (*SCCancelReadyNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SCCancelReadyNtf) GetUinfo() *UserInfo {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

type SCGameStartNtf struct {
}

func (m *SCGameStartNtf) Reset()                    { *m = SCGameStartNtf{} }
func (m *SCGameStartNtf) String() string            { return proto.CompactTextString(m) }
func (*SCGameStartNtf) ProtoMessage()               {}
func (*SCGameStartNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type SCGameEndNtf struct {
}

func (m *SCGameEndNtf) Reset()                    { *m = SCGameEndNtf{} }
func (m *SCGameEndNtf) String() string            { return proto.CompactTextString(m) }
func (*SCGameEndNtf) ProtoMessage()               {}
func (*SCGameEndNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type SCRoundEndNtf struct {
}

func (m *SCRoundEndNtf) Reset()                    { *m = SCRoundEndNtf{} }
func (m *SCRoundEndNtf) String() string            { return proto.CompactTextString(m) }
func (*SCRoundEndNtf) ProtoMessage()               {}
func (*SCRoundEndNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func init() {
	proto.RegisterType((*UserInfo)(nil), "protocol.UserInfo")
	proto.RegisterType((*KeepAlive)(nil), "protocol.KeepAlive")
	proto.RegisterType((*CSLoginReq)(nil), "protocol.CSLoginReq")
	proto.RegisterType((*SCLoginRsp)(nil), "protocol.SCLoginRsp")
	proto.RegisterType((*CSCreateRoomReq)(nil), "protocol.CSCreateRoomReq")
	proto.RegisterType((*SCCreateRoomRsp)(nil), "protocol.SCCreateRoomRsp")
	proto.RegisterType((*CSEnterRoomReq)(nil), "protocol.CSEnterRoomReq")
	proto.RegisterType((*SCEnterRoomRsp)(nil), "protocol.SCEnterRoomRsp")
	proto.RegisterType((*SCEnterRoomNtf)(nil), "protocol.SCEnterRoomNtf")
	proto.RegisterType((*SCRoomUserInfos)(nil), "protocol.SCRoomUserInfos")
	proto.RegisterType((*CSLeaveRoomReq)(nil), "protocol.CSLeaveRoomReq")
	proto.RegisterType((*SCLeaveRoomRsp)(nil), "protocol.SCLeaveRoomRsp")
	proto.RegisterType((*SCLeaveRoomNtf)(nil), "protocol.SCLeaveRoomNtf")
	proto.RegisterType((*SCGameRoomInfo)(nil), "protocol.SCGameRoomInfo")
	proto.RegisterType((*CSReadyReq)(nil), "protocol.CSReadyReq")
	proto.RegisterType((*SCReadyRsp)(nil), "protocol.SCReadyRsp")
	proto.RegisterType((*SCReadyNtf)(nil), "protocol.SCReadyNtf")
	proto.RegisterType((*CSCancelReadyReq)(nil), "protocol.CSCancelReadyReq")
	proto.RegisterType((*SCCancelReadyRsp)(nil), "protocol.SCCancelReadyRsp")
	proto.RegisterType((*SCCancelReadyNtf)(nil), "protocol.SCCancelReadyNtf")
	proto.RegisterType((*SCGameStartNtf)(nil), "protocol.SCGameStartNtf")
	proto.RegisterType((*SCGameEndNtf)(nil), "protocol.SCGameEndNtf")
	proto.RegisterType((*SCRoundEndNtf)(nil), "protocol.SCRoundEndNtf")
	proto.RegisterEnum("protocol.GameId", GameId_name, GameId_value)
	proto.RegisterEnum("protocol.RoomState", RoomState_name, RoomState_value)
	proto.RegisterEnum("protocol.LeaveReason", LeaveReason_name, LeaveReason_value)
	proto.RegisterEnum("protocol.RoomCloseReason", RoomCloseReason_name, RoomCloseReason_value)
	proto.RegisterEnum("protocol.UserGameState", UserGameState_name, UserGameState_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6f, 0xda, 0x3c,
	0x14, 0x25, 0x84, 0x50, 0xb8, 0x40, 0xb1, 0xac, 0xea, 0x13, 0xfa, 0x9e, 0x10, 0xfa, 0x3e, 0x09,
	0xf1, 0xd0, 0x87, 0x4d, 0x9a, 0xa6, 0x6d, 0x0f, 0x5b, 0x53, 0xb6, 0x75, 0xad, 0xd8, 0x94, 0xa8,
	0xea, 0xb3, 0x97, 0x98, 0x36, 0x25, 0xb1, 0xa9, 0x63, 0xda, 0xb5, 0x3f, 0x64, 0xbf, 0x77, 0xba,
	0x76, 0x02, 0xe9, 0x34, 0xd0, 0x78, 0xc2, 0xe7, 0xfa, 0x9e, 0x73, 0xcf, 0xb1, 0x1d, 0xa0, 0x1b,
	0xc9, 0x2c, 0x93, 0xe2, 0x78, 0xa9, 0xa4, 0x96, 0xb4, 0x65, 0x7e, 0x22, 0x99, 0x8e, 0x7e, 0x3a,
	0xd0, 0xba, 0xcc, 0xb9, 0x3a, 0x13, 0x73, 0x49, 0xff, 0x81, 0xe6, 0x2a, 0xe7, 0x2a, 0x89, 0x07,
	0xce, 0xd0, 0x19, 0xbb, 0x41, 0x81, 0xe8, 0xbf, 0xd0, 0x12, 0x49, 0xb4, 0x10, 0x2c, 0xe3, 0x83,
	0xfa, 0xd0, 0x19, 0xb7, 0x83, 0x35, 0x46, 0xce, 0x0d, 0x67, 0x31, 0x57, 0x03, 0xd7, 0xec, 0x14,
	0x88, 0x52, 0x68, 0xe4, 0x9c, 0xe9, 0x41, 0x63, 0xe8, 0x8c, 0xbd, 0xc0, 0xac, 0xe9, 0x11, 0x78,
	0xb9, 0x66, 0x9a, 0x0f, 0xbc, 0xa1, 0x33, 0xee, 0x05, 0x16, 0x60, 0xf5, 0x36, 0x66, 0x9a, 0x0d,
	0x9a, 0x46, 0xc0, 0x82, 0x51, 0x07, 0xda, 0xe7, 0x9c, 0x2f, 0x3f, 0xa4, 0xc9, 0x3d, 0x1f, 0xa5,
	0x00, 0x7e, 0x78, 0x21, 0xaf, 0x13, 0x11, 0xf0, 0x3b, 0x3a, 0x80, 0x03, 0x16, 0x45, 0x72, 0x25,
	0xb4, 0xf1, 0xd9, 0x0e, 0x4a, 0x88, 0x66, 0x96, 0x2c, 0xcf, 0x1f, 0xe2, 0xc2, 0x66, 0x81, 0xb0,
	0x7e, 0xcd, 0x32, 0x9e, 0xc4, 0xc6, 0xa4, 0x17, 0x14, 0x68, 0x33, 0xba, 0x51, 0x1d, 0x1d, 0x00,
	0x84, 0xbe, 0x9d, 0x96, 0x2f, 0x91, 0xab, 0x78, 0xbe, 0x4a, 0xed, 0x30, 0x2f, 0x28, 0x50, 0x45,
	0xb3, 0xfe, 0x67, 0x4d, 0xb7, 0xaa, 0xb9, 0x80, 0xbe, 0x1f, 0xfa, 0x8a, 0x33, 0xcd, 0x03, 0x29,
	0x33, 0x8c, 0xb1, 0x31, 0xeb, 0x3c, 0x33, 0x7b, 0x04, 0x9e, 0x0d, 0x67, 0x75, 0x2d, 0xc0, 0xaa,
	0x92, 0x2b, 0x51, 0x26, 0xb0, 0x60, 0x4b, 0x80, 0x2b, 0xe8, 0x87, 0x7e, 0x65, 0xd8, 0xee, 0x14,
	0x4a, 0xca, 0xac, 0x48, 0xe1, 0x06, 0x05, 0xda, 0x92, 0xe2, 0x3d, 0x1c, 0xfa, 0xe1, 0x54, 0x68,
	0xae, 0x2a, 0x21, 0x0a, 0xbe, 0xf3, 0x8c, 0xbf, 0xe5, 0x26, 0x50, 0x21, 0xf4, 0x37, 0x0a, 0xfb,
	0x3b, 0x1b, 0xbd, 0x79, 0xa6, 0x30, 0xd3, 0x73, 0x3a, 0x06, 0x6f, 0x95, 0x88, 0xb9, 0x34, 0x02,
	0x9d, 0x17, 0xf4, 0xb8, 0x7c, 0xdd, 0xc7, 0xe5, 0xcb, 0x0e, 0x6c, 0xc3, 0xe8, 0x2d, 0x1e, 0x0c,
	0xd2, 0xca, 0x8d, 0xbc, 0x4a, 0x76, 0x77, 0x93, 0xc7, 0x18, 0xfe, 0x82, 0xb3, 0xfb, 0xea, 0x0d,
	0x2a, 0xce, 0x72, 0x29, 0x36, 0xd6, 0x11, 0x61, 0x67, 0xe8, 0x6f, 0x3a, 0xb7, 0x87, 0xb4, 0x61,
	0xd6, 0x9d, 0xfb, 0x85, 0x31, 0xdc, 0x4f, 0x2c, 0x33, 0x54, 0xf3, 0xfd, 0xfe, 0x3d, 0xb7, 0x8b,
	0x1f, 0x54, 0xc0, 0x59, 0xfc, 0x18, 0xf0, 0xbb, 0xd1, 0x7f, 0xf8, 0xe0, 0x2d, 0xda, 0xe1, 0xf5,
	0xd5, 0xba, 0x6b, 0x3f, 0x9f, 0x14, 0x88, 0x1f, 0xfa, 0x4c, 0x44, 0x3c, 0x5d, 0x4f, 0x9c, 0x00,
	0x09, 0xfd, 0x6a, 0x6d, 0xc7, 0xdc, 0x77, 0xbf, 0xf5, 0xee, 0x37, 0x9d, 0x94, 0xa7, 0x14, 0x6a,
	0xa6, 0xf4, 0x4c, 0xcf, 0x47, 0x87, 0xd0, 0xb5, 0x95, 0xa9, 0x88, 0x11, 0xf7, 0xa1, 0x87, 0x8f,
	0x62, 0x25, 0x62, 0x5b, 0x98, 0xfc, 0x0f, 0x4d, 0xdc, 0x3e, 0x8b, 0x69, 0x0b, 0x1a, 0x33, 0x29,
	0x38, 0xa9, 0xe1, 0xea, 0xf3, 0x53, 0x76, 0x4b, 0x38, 0x3d, 0x00, 0xf7, 0x34, 0x7e, 0x22, 0xf3,
	0xc9, 0x6b, 0x68, 0xe3, 0xc9, 0x87, 0xe6, 0x4f, 0xac, 0x05, 0x8d, 0xb3, 0x38, 0x2d, 0x3a, 0xaf,
	0x58, 0xa2, 0x89, 0x43, 0xc1, 0xe8, 0x24, 0xe2, 0x9a, 0xd4, 0x69, 0x07, 0x0e, 0xfc, 0x54, 0xe6,
	0x08, 0xdc, 0xc9, 0x17, 0xe8, 0xd8, 0x3b, 0x37, 0xcf, 0x05, 0xf7, 0x2e, 0xc5, 0x42, 0xc8, 0x07,
	0x41, 0x6a, 0xb4, 0x07, 0x6d, 0x5f, 0x0a, 0x71, 0xa2, 0x38, 0x5b, 0x10, 0x07, 0xd5, 0xce, 0x93,
	0x68, 0x41, 0xea, 0xb4, 0x0d, 0xde, 0x47, 0xa9, 0x22, 0x4e, 0x5c, 0x14, 0xc6, 0x98, 0x5f, 0x97,
	0xa4, 0x31, 0x39, 0x85, 0x3e, 0xba, 0x40, 0xf1, 0x52, 0x0f, 0xa0, 0x39, 0x93, 0x2a, 0x63, 0x29,
	0xa9, 0xe1, 0x7a, 0xfa, 0x63, 0x99, 0x28, 0x4e, 0x1c, 0x7a, 0x08, 0x60, 0x14, 0x4c, 0xaf, 0x55,
	0x9c, 0x66, 0x4b, 0xfd, 0x48, 0xdc, 0xc9, 0x09, 0xf4, 0x50, 0xb1, 0x38, 0x27, 0xcd, 0x69, 0x17,
	0x5a, 0x57, 0x4c, 0x47, 0x37, 0x68, 0xb8, 0x66, 0x1d, 0x9a, 0xc3, 0x27, 0x0e, 0xd2, 0xec, 0xd2,
	0xa4, 0xfa, 0x96, 0xb2, 0x47, 0x93, 0xea, 0x7b, 0xd3, 0xdc, 0xc1, 0xcb, 0x5f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x55, 0x1e, 0x99, 0x2b, 0x6b, 0x06, 0x00, 0x00,
}
